# Generated by Django 4.2.8 on 2024-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_is_active_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
