# Generated by Django 4.2.10 on 2024-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='default_background.jpg', upload_to='user_backgrounds'),
        ),
    ]
