# Generated by Django 4.2.10 on 2024-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_photos'),
        ),
    ]
