# Generated by Django 5.0 on 2024-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='book_id',
            new_name='book',
        ),
    ]
