# Generated by Django 5.0 on 2024-02-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='chapter_number',
        ),
    ]
