# Generated by Django 4.2.10 on 2024-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
