# Generated by Django 5.0 on 2024-02-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_book_id_interaction_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='chapters',
        ),
    ]
