# Generated by Django 5.0 on 2024-02-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_interaction_chapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
