# Generated by Django 4.2.8 on 2024-04-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_usergenrepreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergenrepreference',
            name='book',
        ),
        migrations.RemoveField(
            model_name='usergenrepreference',
            name='genre_preferences',
        ),
        migrations.AddField(
            model_name='usergenrepreference',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.genre'),
            preserve_default=False,
        ),
    ]
