# Generated by Django 4.2.10 on 2024-04-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
