# Generated by Django 4.2.8 on 2024-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_usergenrepreference_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergenrepreference',
            name='genre',
        ),
        migrations.AddField(
            model_name='usergenrepreference',
            name='preferred_genres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
