# Generated by Django 5.0 on 2024-02-22 13:21

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='chapter',
            field=models.FileField(upload_to=base.models.upload_chapter_path),
        ),
    ]
