# Generated by Django 4.2.8 on 2024-04-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_usergenrepreference_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGenrePreference',
        ),
    ]
