# Generated by Django 4.2.8 on 2024-04-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_userpreferredgenre_genres_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferredgenre',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userpreferredgenre',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
