export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const CREATE_REPLY_REQUEST = 'CREATE_REPLY_REQUEST';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_FAIL = 'CREATE_REPLY_FAIL';

export const GET_REPLIES_REQUEST = 'GET_REPLIES_REQUEST';
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS';
export const GET_REPLIES_FAIL = 'GET_REPLIES_FAIL';



export const GET_USER_COMMENTS_AND_REPLIES_REQUEST = 'GET_USER_COMMENTS_AND_REPLIES_REQUEST';
export const GET_USER_COMMENTS_AND_REPLIES_SUCCESS = 'GET_USER_COMMENTS_AND_REPLIES_SUCCESS';
export const GET_USER_COMMENTS_AND_REPLIES_FAILURE = 'GET_USER_COMMENTS_AND_REPLIES_FAILURE';
