export const USER_FEEDBACK_REQUEST = "USER_FEEDBACK_REQUEST";
export const USER_FEEDBACK_SUCCESS = "USER_FEEDBACK_SUCCESS";
export const USER_FEEDBACK_FAIL = "USER_FEEDBACK_FAIL";
export const USER_FEEDBACK_RESET = "USER_FEEDBACK_RESET";

export const USER_FEEDBACK_LIST_REQUEST = "USER_FEEDBACK_LIST_REQUEST";
export const USER_FEEDBACK_LIST_SUCCESS = "USER_FEEDBACK_LIST_SUCCESS";
export const USER_FEEDBACK_LIST_FAIL = "USER_FEEDBACK_LIST_FAIL";

export const USER_FEEDBACK_DELETE_REQUEST = "USER_FEEDBACK_DELETE_REQUEST";
export const USER_FEEDBACK_DELETE_SUCCESS = "USER_FEEDBACK_DELETE_SUCCESS";
export const USER_FEEDBACK_DELETE_FAIL = "USER_FEEDBACK_DELETE_FAIL";
export const USER_FEEDBACK_DELETE_RESET = "USER_FEEDBACK_DELETE_RESET";
