export const USER_FEEDBACK_REQUEST = 'USER_FEEDBACK_REQUEST'
export const USER_FEEDBACK_SUCCESS = 'USER_FEEDBACK_SUCCESS'
export const USER_FEEDBACK_FAIL = 'USER_FEEDBACK_FAIL'
export const USER_FEEDBACK_RESET = 'USER_FEEDBACK_RESET'