export const GENRE_LIST_REQUEST = 'GENRE_LIST_REQUEST';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL';

export const GENRE_DETAILS_REQUEST = 'GENRE_DETAILS_REQUEST';
export const GENRE_DETAILS_SUCCESS = 'GENRE_DETAILS_SUCCESS';
export const GENRE_DETAILS_FAIL = 'GENRE_DETAILS_FAIL';


