export const INTERACTION_LIST_REQUEST = 'INTERACTION_LIST_REQUEST';
export const INTERACTION_LIST_SUCCESS = 'INTERACTION_LIST_SUCCESS';
export const INTERACTION_LIST_FAIL = 'INTERACTION_LIST_FAIL';

export const INTERACTION_DETAILS_REQUEST = 'INTERACTION_DETAILS_REQUEST';
export const INTERACTION_DETAILS_SUCCESS = 'INTERACTION_DETAILS_SUCCESS';
export const INTERACTION_DETAILS_FAIL = 'INTERACTION_DETAILS_FAIL';

export const INTERACTION_LIST_BY_BOOK_FAIL = 'INTERACTION_LIST_BY_BOOK_FAIL';
export const INTERACTION_LIST_BY_BOOK_REQUEST = 'INTERACTION_LIST_BY_BOOK_REQUEST';
export const INTERACTION_LIST_BY_BOOK_SUCCESS = 'INTERACTION_LIST_BY_BOOK_SUCCESS';
