export const INTERACTION_LIST_REQUEST = 'INTERACTION_LIST_REQUEST';
export const INTERACTION_LIST_SUCCESS = 'INTERACTION_LIST_SUCCESS';
export const INTERACTION_LIST_FAIL = 'INTERACTION_LIST_FAIL';

export const INTERACTION_DETAILS_REQUEST = 'INTERACTION_DETAILS_REQUEST';
export const INTERACTION_DETAILS_SUCCESS = 'INTERACTION_DETAILS_SUCCESS';
export const INTERACTION_DETAILS_FAIL = 'INTERACTION_DETAILS_FAIL';

export const INTERACTION_LIST_BY_BOOK_FAIL = 'INTERACTION_LIST_BY_BOOK_FAIL';
export const INTERACTION_LIST_BY_BOOK_REQUEST = 'INTERACTION_LIST_BY_BOOK_REQUEST';
export const INTERACTION_LIST_BY_BOOK_SUCCESS = 'INTERACTION_LIST_BY_BOOK_SUCCESS';

export const INTERACTION_CREATE_REQUEST =  'INTERACTION_CREATE_REQUEST'
export const INTERACTION_CREATE_SUCCESS =  'INTERACTION_CREATE_SUCCESS'
export const INTERACTION_CREATE_FAIL =  'INTERACTION_CREATE_FAIL'
export const INTERACTION_CREATE_RESET =  'INTERACTION_CREATE_RESET'

export const INTERACTION_UPDATE_REQUEST = 'INTERACTION_UPDATE_REQUEST'
export const INTERACTION_UPDATE_SUCCESS = 'INTERACTION_UPDATE_SUCCESS'
export const INTERACTION_UPDATE_FAIL = 'INTERACTION_UPDATE_FAIL'
export const INTERACTION_UPDATE_RESET = 'INTERACTION_UPDATE_RESET'

export const INTERACTION_DELETE_REQUEST = 'INTERACTION_DELETE_REQUEST'
export const INTERACTION_DELETE_SUCCESS = 'INTERACTION_DELETE_SUCCESS'
export const INTERACTION_DELETE_FAIL = 'INTERACTION_DELETE_FAIL'
export const INTERACTION_DELETE_RESET = 'INTERACTION_DELETE_RESET'

