export const ADD_TO_READING_HISTORY_REQUEST = 'ADD_TO_READING_HISTORY_REQUEST';
export const ADD_TO_READING_HISTORY_SUCCESS = 'ADD_TO_READING_HISTORY_SUCCESS';
export const ADD_TO_READING_HISTORY_FAILURE = 'ADD_TO_READING_HISTORY_FAILURE';

export const GET_PREFERRED_GENRE_REQUEST = 'GET_PREFERRED_GENRE_REQUEST';
export const GET_PREFERRED_GENRE_SUCCESS = 'GET_PREFERRED_GENRE_SUCCESS';
export const GET_PREFERRED_GENRE_FAILURE = 'GET_PREFERRED_GENRE_FAILURE';