export const ADD_TO_READING_HISTORY_REQUEST = 'ADD_TO_READING_HISTORY_REQUEST';
export const ADD_TO_READING_HISTORY_SUCCESS = 'ADD_TO_READING_HISTORY_SUCCESS';
export const ADD_TO_READING_HISTORY_FAILURE = 'ADD_TO_READING_HISTORY_FAILURE';

export const GET_RECOMMENDED_BOOKS_REQUEST = 'GET_RECOMMENDED_BOOKS_REQUEST';
export const GET_RECOMMENDED_BOOKS_SUCCESS = 'GET_RECOMMENDED_BOOKS_SUCCESS';
export const GET_RECOMMENDED_BOOKS_FAILURE = 'GET_RECOMMENDED_BOOKS_FAILURE';

export const SET_PREFERRED_GENRE_REQUEST = 'SET_PREFERRED_GENRE_REQUEST';
export const SET_PREFERRED_GENRE_SUCCESS = 'SET_PREFERRED_GENRE_SUCCESS';
export const SET_PREFERRED_GENRE_FAILURE = 'SET_PREFERRED_GENRE_FAILURE';

export const GET_PREFERRED_GENRES_REQUEST = 'GET_PREFERRED_GENRES_REQUEST';
export const GET_PREFERRED_GENRES_SUCCESS = 'GET_PREFERRED_GENRES_SUCCESS';
export const GET_PREFERRED_GENRES_FAILURE = 'GET_PREFERRED_GENRES_FAILURE';

export const GET_RANDOM_BOOKS_REQUEST = 'GET_RANDOM_BOOKS_REQUEST';
export const GET_RANDOM_BOOKS_SUCCESS = 'GET_RANDOM_BOOKS_SUCCESS';
export const GET_RANDOM_BOOKS_FAILURE = 'GET_RANDOM_BOOKS_FAILURE';