export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const GET_USER_PROFILE_BY_ID_REQUEST = "GET_USER_PROFILE_BY_ID_REQUEST";
export const GET_USER_PROFILE_BY_ID_SUCCESS = "GET_USER_PROFILE_BY_ID_SUCCESS";
export const GET_USER_PROFILE_BY_ID_FAIL = "GET_USER_PROFILE_BY_ID_FAIL";

export const LATEST_USER_READING_HISTORY_REQUEST =
  "LATEST_USER_READING_HISTORY_REQUEST";
export const LATEST_USER_READING_HISTORY_SUCCESS =
  "LATEST_USER_READING_HISTORY_SUCCESS";
export const LATEST_USER_READING_HISTORY_FAIL =
  "LATEST_USER_READING_HISTORY_FAIL";
