export const FETCH_RATINGS_REQUEST = "FETCH_RATINGS_REQUEST";
export const FETCH_RATINGS_SUCCESS = "FETCH_RATINGS_SUCCESS";
export const FETCH_RATINGS_FAILURE = "FETCH_RATINGS_FAILURE";

export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "CREATE_RATING_FAILURE";

export const UPDATE_RATING_REQUEST = "UPDATE_RATING_REQUEST";
export const UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS";
export const UPDATE_RATING_FAILURE = "UPDATE_RATING_FAILURE";

export const DELETE_RATING_REQUEST = "DELETE_RATING_REQUEST";
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS";
export const DELETE_RATING_FAILURE = "DELETE_RATING_FAILURE";

export const GET_RATING_ID_REQUEST = "GET_RATING_ID_REQUEST";
export const GET_RATING_ID_SUCCESS = "GET_RATING_ID_SUCCESS";
export const GET_RATING_ID_FAILURE = "GET_RATING_ID_FAILURE";

export const FETCH_RATING_REQUEST = "FETCH_RATING_REQUEST";
export const FETCH_RATING_SUCCESS = "FETCH_RATING_SUCCESS";
export const FETCH_RATING_FAILURE = "FETCH_RATING_FAILURE";
