export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_PAID_REQUEST = "USER_UPDATE_PAID_REQUEST";
export const USER_UPDATE_PAID_SUCCESS = "USER_UPDATE_PAID_SUCCESS";
export const USER_UPDATE_PAID_FAIL = "USER_UPDATE_PAID_FAIL";
export const USER_UPDATE_PAID_RESET = "USER_UPDATE_PAID_RESET";

export const CHECK_PAID_STATUS_REQUEST = 'CHECK_PAID_STATUS_REQUEST';
export const CHECK_PAID_STATUS_SUCCESS = 'CHECK_PAID_STATUS_SUCCESS';
export const CHECK_PAID_STATUS_FAILURE = 'CHECK_PAID_STATUS_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
