export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_PAID_REQUEST = "USER_UPDATE_PAID_REQUEST";
export const USER_UPDATE_PAID_SUCCESS = "USER_UPDATE_PAID_SUCCESS";
export const USER_UPDATE_PAID_FAIL = "USER_UPDATE_PAID_FAIL";
export const USER_UPDATE_PAID_RESET = "USER_UPDATE_PAID_RESET";

export const CHECK_PAID_STATUS_REQUEST = 'CHECK_PAID_STATUS_REQUEST';
export const CHECK_PAID_STATUS_SUCCESS = 'CHECK_PAID_STATUS_SUCCESS';
export const CHECK_PAID_STATUS_FAILURE = 'CHECK_PAID_STATUS_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';